---
- name: User Creation, Subscription Management, and Update Status
  hosts: master
  gather_facts: true
  become: yes
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: testuser
        state: present
        shell: /bin/bash
        groups: users
        append: yes

  