---
- name: User Creation, Subscription Management, and Update Status
  hosts: master
  gather_facts: true
  become: yes
  tasks:


    - name: Remove Existing Subscription
      command: subscription-manager remove --all
      ignore_errors: true

    - name: Register System with New Subscription
      command: subscription-manager register --username=vaidhiyanathan --password=vaidhi@0212 --auto-attach


    - name: Get subscription-manager status
      command: subscription-manager status
      register: output

    - name: Save output to a file
      copy:
        content: "{{ output.stdout }}"
        dest: /home/vaidhi/Documents/Playbooks/output.txt

    - name: Copy Results to Control Machine
      ansible.builtin.fetch:
        src: "/home/vaidhi/Documents/Playbooks/output.txt"
        dest: "/home/vaidhi/Documents/Playbooks/output.txt"